[project]
authors = ["Pierre Poulain <pierre.poulain@cupnet.net>"]
channels = ["conda-forge", "bioconda", "nodefaults"]
description = "Environment for Jupyter Lab"
name = "jupyterlab-demo"
platforms = ["linux-64", "osx-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.12"
numpy = "*"
pandas = "*"
matplotlib = "*"
jupyterlab = ">=4"
ipywidgets = "*"
r-irkernel = "*"
r-base = ">=4.0"
r-tidyverse = "*"

[pypi-dependencies]
bash-kernel = "*"
watermark = "*"
