name: jupyter-demo
channels:
    - defaults
    - conda-forge
dependencies:
    - python=3.7
    - numpy
    - scipy
    - pandas
    - matplotlib
    - bokeh
    - jupyterlab
    - ipywidgets
    - r-irkernel
    - nodejs