name: jupyter-demo
# channels priority
# see https://bioconda.github.io/
# conda-forge has highest priority
channels:
    - defaults
    - bioconda
    - conda-forge
dependencies:
    - python=3.8
    - pip
    - numpy
    - pandas
    - matplotlib
    - jupyterlab>=3
    - ipywidgets
    - nodejs
    - r-irkernel
    - r-base>=4.0
    - r-tidyverse
    - pip:
        - bash_kernel
