name: jupyter-demo
channels:
    - conda-forge
    - bioconda
    - nodefaults
dependencies:
    - python
    - pip
    - numpy
    - pandas
    - matplotlib
    - jupyterlab>=4
    - ipywidgets
    - r-irkernel
    - r-base>=4.0
    - r-tidyverse
    # For DUO example with DESeq2
    #- bioconductor-deseq2
    #- bioconductor-parathyroidse
    - pip:
        - bash_kernel
        - watermark
